print("Γεια σας κόσμο is how you say Hello world in Greek.")
print("Olá Mundo is how you say hello world in Portugese.")
print("Ahoj světe is how you say hello world in Czech.")
print("안녕 세상 is how you say hello world in Korean.")
print("你好，世界 is how you say hello world in Chinese.")
print("नमस्ते दुनिया is how you say hello world in Hindi.")
print("Salamu, Dunia is hello world in Swahilli.")
print("םלוע םולש is hello world in Hebrew.")
